name = "yeezy"
category = "essentials"

date = "2026-06-20"

price = "~45.00"
stock = '...'

description = "sznx sznx sznx sznx sznx sznx"

html = """
<iframe src="https://yeezy.com/" width="100%" height="400px" style="border:none;">
    GO VISIT YEEZY.COM RIGHT NOW
</iframe>
"""

# infoMBC = """
# print('abc')
# """

# viewMBC = """
# print('abc')
# """