title = "shop released today."
date = "2026-04-15"

body = """
today I released the CBFP shop for people to buy the latest collects
which have been selling on the streets for a while now.

it's been a project thats been a range of research and long time
friends coming together to make an Art Story that really shows
the past

and how important it is to not accidentally 
erase the past.

<fieldset>
    <legend>what is CBFP?</legend>"Confidence Bank Frat Party" (as "CBFP") is an art project that reaches new heights.

    The latest Collections are:

    <i>XX/2024-05/2025: CLXSSIC</i>
    <i>05/2026-07/2026: YXXXLION</i>

    <i>05/2026-XX/XXXX: LXXXPARD</i>
</fieldset>
"""

viewMBC = """

"""