title = "YXXS 4"
href = "#/posts/yxxs-batch-4"

timestamp = 1781919150

mbc = """
<b>5:33 AM</b>
<b>Trump Debuts Qatar-Gifted Air Force One</b>
<b>Blake, Wm. Newton. 1795.</b>
President Trump unveils luxury Boeing 747 donated by Qatar as new Air Force One.
"""