title = "YXXS 5"
href = "#/posts/yxxs-batch-5"

timestamp = 1781919210

mbc = """
<b>5:32 AM</b>
<b>OpenAI Hires Gemini Co-Lead</b>
<b>Blake, Wm. The Ancient of Days. 1794.</b>
OpenAI recruits Google's Noam Shazeer amid AI talent race.
"""