title = "YXXS 2"
href = "#/posts/yxxs-batch-2"

timestamp = 1781918106

mbc = """
<b>1:14 AM</b>
<b>UK Train Crash Kills One, Injures Dozens</b>
<b>Blake, Wm. The Circle of the Lustful. 1827.</b>
Trains collide near Bedford. Emergency services respond to tragic crash.
"""