title = "YXXS 1"
href = "#/posts/yxxs-batch-1"

timestamp = 1781918074

mbc = """
<b>1:14 AM</b>
<b>Israel-Hezbollah Ceasefire Renewed Amid Iran Talks</b>
<b>Blake, Wm. The Ancient of Days. 1794.</b>
Truce renewed amid Iran talks. U.S. envoy heads to negotiations.
"""